"""empty message

Revision ID: 070247d89e69
Revises: 0763d677d453
Create Date: 2025-05-21 09:14:59.394454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070247d89e69'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errand',
    sa.Column('errand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('instructions', sa.String(length=250), nullable=False),
    sa.Column('requirements', sa.String(length=2083), nullable=False),
    sa.Column('country', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('errand_id')
    )
    op.create_table('offices',
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=250), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('errand_type',
    sa.Column('errand_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('errand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['errand_id'], ['errand.errand_id'], ),
    sa.PrimaryKeyConstraint('errand_type_id')
    )
    op.create_table('favorites',
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('errand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['errand_id'], ['errand.errand_id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('favorites_id')
    )
    op.create_table('follow_up',
    sa.Column('follow_up_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('errand_name', sa.String(length=250), nullable=False),
    sa.Column('status_type', sa.Enum('Iniciado', 'finalizado', name='status_enum'), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('follow_up_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('follow_up')
    op.drop_table('favorites')
    op.drop_table('errand_type')
    op.drop_table('users')
    op.drop_table('offices')
    op.drop_table('errand')
    # ### end Alembic commands ###
