"""empty message

Revision ID: 1c4648f098fa
Revises: 070247d89e69
Create Date: 2025-05-21 10:01:36.362532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4648f098fa'
down_revision = '070247d89e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'offices', ['office_id'], ['office_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('office_id')

    # ### end Alembic commands ###
