"""empty message

Revision ID: 4ac61c301949
Revises: 1c4648f098fa
Create Date: 2025-05-21 13:33:34.513720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac61c301949'
down_revision = '1c4648f098fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('errand_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'errand_type', ['errand_type_id'], ['errand_type_id'])

    with op.batch_alter_table('errand_type', schema=None) as batch_op:
        batch_op.drop_constraint('errand_type_errand_id_fkey', type_='foreignkey')
        batch_op.drop_column('errand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('errand_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('errand_type_errand_id_fkey', 'errand', ['errand_id'], ['errand_id'])

    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('errand_type_id')

    # ### end Alembic commands ###
