"""empty message

Revision ID: 5b6e01d83b71
Revises: 4ac61c301949
Create Date: 2025-05-23 14:05:34.208022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6e01d83b71'
down_revision = '4ac61c301949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedures', sa.String(length=250), nullable=False))
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('instructions')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('instructions', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('procedures')

    # ### end Alembic commands ###
