"""empty message

Revision ID: 808b1e1658a7
Revises: 5b6e01d83b71
Create Date: 2025-05-23 15:07:50.226912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808b1e1658a7'
down_revision = '5b6e01d83b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.alter_column('procedures',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=4500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errand', schema=None) as batch_op:
        batch_op.alter_column('procedures',
               existing_type=sa.String(length=4500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
