"""empty message

Revision ID: 80bb70622d53
Revises: 525fed170512
Create Date: 2025-06-01 17:23:16.769793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bb70622d53'
down_revision = '525fed170512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2083),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
