"""empty message

Revision ID: e15bb319f981
Revises: 525fed170512
Create Date: 2025-06-01 20:14:04.613850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e15bb319f981'
down_revision = '525fed170512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('documentacion', sa.String(length=2038), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=2038), nullable=True))
        batch_op.alter_column('form_data',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2038),
               existing_nullable=True)
        batch_op.drop_column('expiration_date')

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2083),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('form_data',
               existing_type=sa.String(length=2038),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('descripcion')
        batch_op.drop_column('documentacion')
        batch_op.drop_column('reference_date')

    # ### end Alembic commands ###
