"""empty message

Revision ID: e9adc51688a0
Revises: 808b1e1658a7
Create Date: 2025-05-26 11:33:18.807565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9adc51688a0'
down_revision = '808b1e1658a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_data', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.drop_column('form_data')

    # ### end Alembic commands ###
